apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vkuj2k1uo-go 
  janus-idp.io/tekton: vkuj2k1uo-go
  backstage.io/kubernetes-id: vkuj2k1uo-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vkuj2k1uo-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml