apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vkuj2k1uo-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vkuj2k1uo-go 
  name: vkuj2k1uo-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vkuj2k1uo-go 
